const data =  [
     {    "id":"0",
     "project_name":"∑tockly",
        "description":"A build week application where I collaborted with a team of engineers and data scientists to simplify the decision in either buying, selling, or holding a specific stock.",
        "technologies":["react-redux","js","css3-alt","html5","sass", "react"],
        "demo":"https://stockly-fe.netlify.com/",
        "sourceCode":"https://github.com/lambda-stockly/build-stockly-frontend",
        landingImage: '/images/stockly.png'
        
     }, 
     {  "id": "1",
        "project_name":"Game Show App",
        "description":"An 'hangman'-esque game by correctly guessing the corresponding letters of a phrase generated by the game.",
        "technologies":["js","css3","html5"],
        "demo":"https://rubenponce.github.io/gameShowApp/",
        "sourceCode":"https://github.com/RubenPonce/gameShowApp/",
        landingImage: '/images/gameshowapp.png'
     },
     {"id" : "2",
      "project_name":"Pinetreach",
        "description":"During Lambda School's Build Week of April 15th to April 19th of 2019, I worked with a team of developers to design and develop the UI/Landing page",
        "technologies":["js","css3-alt","html5","less"],
        "demo":"https://pintereachui.netlify.com/",
        "sourceCode":"https://github.com/pintreach/buildweek-pintreach-UI",
        landingImage: '/images/pintreach.png'
     },
     
    ]
  
  export default data