const data =  [
     {    "id":"1",
        "project_name":"Pinetreach",
        "description":"During Lambda School's Build Week of April 15th to April 19th of 2019, I worked with a team of developers to design and develop the UI/Landing page",
        "technologies":["js","css3-alt","html5","less"],
        "demo":"https://pintereachui.netlify.com/",
        "sourceCode":"https://github.com/pintreach/buildweek-pintreach-UI",
        landingImage: './images/pine.png'
     }, 
     {  "id": "4",
        "project_name":"Technical Word Salad",
        "description":"An 'hangman'-esque game by correctly guessing the corresponding letters of a phrase generated by the game.",
        "technologies":["js","css3","html5"],
        "demo":"https://rubenponce.github.io/gameShowApp/",
        "sourceCode":"https://github.com/RubenPonce/gameShowApp/",
        landingImage: './images/wordsalad.png'
     },
     
    ]
  
  export default data